### ISSUE TITLE
Supporting Atom

### ISSUE THREAD

**Issue by brettz9** [fisker/editor-info#1]
Hi @fisker ,

Logging `process.env` in Atom's console shows only one property with "ATOM" in it, namely `ATOM_HOME` pointing to the `.atom` folder in one's user directory.

I confirmed that this should work (conditionally throwing when `process.env.ATOM_HOME` is present, noticing that when running from CLI, it worked, while within Atom, it did not).

There are official docs about it at https://flight-manual.atom.io/using-atom/sections/basic-customization/#custom-home-location-with-an-environment-variable .

Not inclined to make a PR at this time, but offering in case you wanted to use it, as I was curious whether this could be made to work with Atom.

**Comment by fisker** [comment]
Thanks, I don't use Atom, but PR welcome.

This package not ready yet, I need a babel transform before I can use it in my `.eslintrc.js` 😄

**Comment by brettz9** [comment]
By the way, let me know when the package is functional so we can add to [`awesome-eslint`](https://github.com/dustinspecker/awesome-eslint).

**Comment by fisker** [comment]
I think it's already functional, I won't do anything related to ESLint here.

**Comment by fisker** [comment]
Fixed by #2

**Comment by fisker** [comment]
Have got something in mind that can use this?

Here is mine:

1. Disable some rule in my personal config
2. Use different fix logic for `eslint-plugin-prettier`

**Comment by brettz9** [comment]
Added to https://github.com/dustinspecker/awesome-eslint#tools . Thanks!

**Comment by brettz9** [comment]
> Have you got something in mind that can use this?

I can't recall at the moment, but I've run into issues where Atom wasn't operating in the same way, causing some false positive IIRC. Might have been an import resolver issue, but can't really recall for sure right now.

**Comment by brettz9** [comment]
This wasn't the one I was thinking of, but here's one issue I found looking at one project's config.

My config sets the `parserOptions.ecmaVersion` dynamically based on the minimum version in `engines`: https://github.com/brettz9/eslint-config-ash-nazg/blob/master/node.js#L3-L18

However, my detection script which [uses `process.cwd`](https://github.com/brettz9/eslint-config-ash-nazg/blob/74e07cd0e108cc8e62d86254a4e0c698f2fbd4e6/detectEnv.js#L90), gets a bad cwd apparently from within Atom.

If I'm going to have to set it manually, I guess I might just drop the dynamic setting approach, but was hoping to find a workaround. :-)
